[build]
builder = "NIXPACKS"
buildCommand = "bash scripts/build.sh"

[deploy]
startCommand = "node .next/standalone/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
